### ISSUE TITLE
How to deploy to heroku nextjs

### ISSUE THREAD

**Issue by ShintaroNippon** [mars/heroku-nextjs-custom-server-express#5]
'm using this code in package.json

"scripts": {
"build": "cd app && next build",
"start": "npm run build && env NODE_ENV=production node app.js",
"dev": "nodemon --ignore app/ app.js" },

And i wanna deploy to heroku app...

I have tried too

"start": "next start -p $PORT",

I'm using this boilerplate: https://github.com/MustansirZia/next-express-bootstrap-boilerplate

Thanks in advance

**Comment by mars** [comment]
Hi @ShintaroNippon,

Same answer as before, you can follow the [Production Deployment](https://github.com/mars/heroku-nextjs/blob/master/README.md#user-content-production-deployment) directions to deploy an existing Next app.
