### ISSUE TITLE
How to pass slug into page component?

### ISSUE THREAD

**Issue by denny64** [mars/heroku-nextjs-custom-server-express#6]
```
server.get('/page/:slug', (req, res) => {
        return nextApp.render(req, res, '/page/[pid].js?slug=$slug', req.params.slug)
      })
```

How can I access the slug from my page component?

**Comment by mars** [comment]
From on the Next docs for [Dynamic Routing](https://nextjs.org/docs#dynamic-routing):

> …the route `/post/abc?foo=bar` will have the query object: `{ foo: 'bar', pid: 'abc' }`.

So, it seems like making query arg an object would work:

```
server.get('/page/:slug', (req, res) => {
        return nextApp.render(req, res, '/page/[pid].js', { slug: req.params.slug })
      })
```

This is my best attempt to lookup some information for you in the Next docs. I can really only speak to the Heroku aspects of this project. If this doesn't help, then this question might have a better chance of being answered in the Next.js community.

**Comment by denny64** [comment]
Thanks, that worked!
